### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by grena** [grena/ldjam46#2]
DONE
- [x] Z index inspectrice
- [x] polaroid + note inspection
- [x] une seule taupe par case
- [x] passer de 0 à 1 coute des sous
- [x] ballons & champignons + rapides à virer
- [x] victoire si photo & toutes les cases vertes
- [x] bruit quand on dégage le ballon
- [x] looper sur le son d'ambiance
- [x] BUG facteur nique 2 health en montant
- [x] animer la perte d'argent
- [x] texte intro
- [x] text splash screen
- [x] balancer
- [x] Confettis

PIPOU TU PRENDS

PIERRE TU PRENDS

TODO
- [x] Bruit de PFFRRR quand on peut pas acheter
- [x] Bruit de pop pour les champis
- [x] Bruit pour dégager les taupes
- [x] Bruit pour l'apparition des taupes
- [x] Son quand on win

++
- [ ] Message "inspector is coming in.."
- [ ] Sprite du supermarché
